apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: skafford
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: truongtrunghieu/ticketing_auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "*.ts"
            dest: .

